name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:

    runs-on: ubuntu-latest

    env:
      API_ID: 1
      API_HASH: 1
      PHONE_NUMBER: 1

    steps:
      - uses: actions/checkout@v2

      - name: formatting
        run: make format-check

      - name: clippy
        run: make lint
