name: Publish

on:
  push:
#    tags:
#      - '*'
#    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
#  check:
#    uses: ./.github/workflows/checks.yml

  publish:
#    needs: [check]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: |
        cargo generate-lockfile
        pkg_version=$(cargo pkgid | cut -d "#" -f2)
        echo $pkg_version
        echo $GITHUB_REF_NAME
        if [[ "$pkg_version" = "$GITHUB_REF_NAME" ]]; then
          echo "equals"
        else
          echo "not equals"
          exit 1
        fi

    - uses: katyo/publish-crates@v2
      with:
        registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        args: --all-features
        dry-run: true
