name: Publish

on:
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/checks.yml

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v2
      with:
        toolchain: stable
        override: true

    - uses: katyo/publish-crates@v2
      with:
        registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        args: --all-features
        dry-run: true
